### ISSUE TITLE
can i change the msg  type for the onrobot gripper ?

### ISSUE THREAD

**Issue by Dorianproject** [takuya-ki/onrobot-rg#3]
Hey i am currently working on a ros2 package for the RG2-FT gripper. Can i change the msgs for example from rGWD to r_gwd, since Ros2 has problems with Cap letters and wont let me build if i do rGWD ...?
Thanks for your response.

**Comment by takuya-ki** [comment]
@Dorianproject 
This repository was not developed for ROS2, so the request cannot be accepted.
Please fork and make your own changes as needed.
